config/routes.rb
Rails.application.routes.draw do
  get 'users/crea'

  get 'users/update1' , to: 'users#update1'

  get 'users/update' , to: 'users#update'

  get 'posts/index1', to: 'posts#index1'
  
  get 'users/index', to: 'users#index'

  get 'home/tasks', to: 'users#tasks'
  
  get 'users/edit' , to: 'users#edit'
  
  get 'users/crea' , to: 'users#crea'

  root 'static_pages#top'
  get '/signup', to: 'users#new'
  get '/tasks', to: 'users#tasks'

  # ログイン機能
  get    '/login', to: 'sessions#new'
  post   '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  

  resources :users do
    member do
      get 'edit_basic_info'
      patch 'update_basic_info'
      get 'attendances/edit_one_month'
      patch 'attendances/update_one_month' # この行が追加対象です。
    end
    resources :attendances, only: :update
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :attendances, dependent: :destroy
  # 「remember_token」という仮想の属性を作成します。
  attr_accessor :remember_token
  before_save { self.email = email.downcase }

  validates :name, presence: true, length: { maximum: 50 }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 100 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: true
  validates :department, length: { in: 2..50 }, allow_blank: true
  validates :basic_time, presence: true
  validates :work_time, presence: true
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  # 渡された文字列のハッシュ値を返します。
  def User.digest(string)
    cost = 
      if ActiveModel::SecurePassword.min_cost
        BCrypt::Engine::MIN_COST
      else
        BCrypt::Engine.cost
      end
    BCrypt::Password.create(string, cost: cost)
  end

  # ランダムなトークンを返します。
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # 永続セッションのためハッシュ化したトークンをデータベースに記憶します。
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # トークンがダイジェストと一致すればtrueを返します。
  def authenticated?(remember_token)
    # ダイジェストが存在しない場合はfalseを返して終了します。
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  # ユーザーのログイン情報を破棄します。
  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def _edit_basic_info
    @users = User.all
  end
  
  def _from
    @users = User.all
  end
  
  def crea
    @users = User.all
  end
  
  def edit
    @users = User.all
  end
  
  def index
    @users = User.all
  end
  
  def new
    @users = User.all
  end
  
  def show
    @users = User.all
  end
  
  def tasks
    @users = User.all
  end
  
  def update
    @users = User.all
  end
  
  def update1
    @users = User.all
  end
  
  
  def login
   @user = User.find_by(email: params[:email], password: params[:password])
  if @user
    flash[:notice] = "ログインしました。"
    redirect_to posts_index_url
    
  else
    flash[:notice] = "認証に失敗しました。"
    render :login_page
  end
  end
  
  def destroy
     # ログイン中の場合のみログアウト処理を実行します。
    log_out if logged_in?
    flash[:success] = 'ログイン状態です。'
    redirect_to posts_index_url
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_edit_basic_info.html.erb
<% provide(:class_text, 'basic-info') %>
<% provide(:button_text, '更新') %>

<div class="modal-dialog modal-lg modal-dialog-center">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      <h1 class="modal-title">基本情報編集</h1>
    </div>
    <div class="modal-body">
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <%= form_with(model: @user, url: update_basic_info_user_path(@user), local: true, method: :patch) do |f| %>
            <%= render 'shared/error_messages', object: @user %>

            <%= f.label :name, class: "label-#{yield(:class_text)}" %>
            <p><%= @user.name %></p>

            <%= f.label :department, class: "label-#{yield(:class_text)}" %>
            <%= f.text_field :department, class: "form-control" %>

            <%= f.label :basic_time, class: "label-#{yield(:class_text)}" %>
            <%= f.time_field :basic_time, class: "form-control" %>

            <%= f.label :work_time, class: "label-#{yield(:class_text)}" %>
            <%= f.time_field :work_time, class: "form-control" %>

            <div class="center">
              <%= f.submit yield(:button_text), class: "btn btn-primary btn-#{yield(:class_text)}" %>
              <button type="button" class="btn btn-default btn-<%= yield(:class_text) %>" data-dismiss="modal">
                キャンセル
              </button>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/_form.html.erb
<%= form_with(model: @user, local: true) do |f| %>
  <%= render 'shared/error_messages', object: @user %>

  <%= f.label :name, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :name, class: "form-control" %>

  <%= f.label :email, class: "label-#{yield(:class_text)}" %>
  <%= f.email_field :email, class: "form-control" %>

  <%= f.label :department, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :department, class: "form-control" %>

  <%= f.label :password, class: "label-#{yield(:class_text)}" %>
  <%= f.password_field :password, class: "form-control" %>

  <%= f.label :password_confirmation, class: "label-#{yield(:class_text)}" %>
  <%= f.password_field :password_confirmation, class: "form-control" %>

  <%= f.submit yield(:button_text), class: "btn btn-primary btn-block btn-#{yield(:class_text)}" %>
<% end %>

app/views/users/basic.html.erb
<% provide(:title, "basic") %>
<% provide(:class_text, 'users/62/basic') %>
<% provide(:button_text, 'ユーザー情報の更新') %>

 <div class="container">
      
<h1>ユーザー情報の更新</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <form action="/users/105" accept-charset="UTF-8" method="post"><input name="utf8" type="hidden" value="&#x2713;" /><input type="hidden" name="_method" value="patch" /><input type="hidden" name="authenticity_token" value="sRxorYRvWGWcyMRhMWLC1n6+FlPmUu8UmONY1rv8qsWJEaqw2Ny+zagBOttN0ktA+E83o8yyFzUisPfye5eblQ==" />
  

  <label class="label-form" for="user_name">名前</label>
  <input class="form-control" type="text" value="CHONO" name="user[name]" />

  <label class="label-form" for="user_email">メールアドレス</label>
  <input class="form-control" type="email" value="chono0316@gmail.com" name="user[email]" />

  <label class="label-form" for="user_password">パスワード</label>
  <input class="form-control" type="password" name="user[password]" />

  <label class="label-form" for="user_password_confirmation">パスワード再入力</label>
  <input class="form-control" type="password" name="user[password_confirmation]" />

  <input type="submit" name="commit" value="更新" class="btn btn-primary btn-block btn-form" data-disable-with="更新" />
</form>
  </div>
</div>
      
    </div>

app/views/users/crea.html.erb
<% provide(:title, 'Crea') %>
<div class="container">
      
<h2>ユーザー登録</h2>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <form action="/users" accept-charset="UTF-8" method="post"><input name="utf8" type="hidden" value="&#x2713;" /><input type="hidden" name="authenticity_token" value="hg55Otl28Xr1vEzZjE+v1fvWnjRzx7gvoljn+uKHu5wYwF/8/4LKJl0Tef2H89Wsk1Bdjxu6fO97WUJlmBLacg==" />
  

  <label class="label-form" for="user_name">名前</label>
  <input class="form-control" type="text" name="user[name]" />

  <label class="label-form" for="user_email">メールアドレス</label>
  <input class="form-control" type="email" name="user[email]" />

  <label class="label-form" for="user_password">パスワード</label>
  <input class="form-control" type="password" name="user[password]" />

  <label class="label-form" for="user_password_confirmation">パスワード再入力</label>
  <input class="form-control" type="password" name="user[password_confirmation]" />

  <input type="submit" name="commit" value="新規登録" class="btn btn-primary btn-block btn-form" data-disable-with="新規登録" />
</form>
  </div>
</div>

      
    </div>

app/views/users/edit.html.erb
<% provide(:title, 'Edit') %>
<% provide(:class_text, 'users/edit') %>
<% provide(:button_text, 'タスク一覧') %>

<div class="container">
      
<h2>CHONOのタスク一覧</h2>


<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <a class="btn btn-lg btn-primary pull-right" <%= link_to "タスク新規作成", users_index_path%></a>
    <table class="table table-hover" id="table-tasks">
      <thead>
        <tr>
          <th>名称</th>
          <th>作成日</th>
          <th></th>
        </tr>
      </thead>

      <tbody>
          <tr>
            <td><a id="task-name" href="/users/105/tasks/158">chono</a></td>
            <td>2019/08/03 23:36</td>
            <td>
              <a class="btn btn-success" <%= link_to "編集", users_update_path%></a>
              <a data-confirm="「chono」を削除します。よろしいですか？" class="btn btn-danger" rel="nofollow" data-method="delete" href="/users/105/tasks/158">削除</a>
            </td>
          </tr>
      </tbody>
    </table>
  </div>    
</div>
      
</div>

app/views/users/edit_basic_info.js.erb
$("#edit-basic-info").html("<%= escape_javascript(render 'edit_basic_info') %>");
$("#edit-basic-info").modal("show");

app/views/users/index.html.erb
<% provide(:title, 'All Users') %>
<h2>タスク新規作成</h2>

<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <form action="/users/62/tasks" accept-charset="UTF-8" method="post"><input name="utf8" type="hidden" value="&#x2713;" /><input type="hidden" name="authenticity_token" value="iU2Otcre2fmvOEGub1VxCaH57peehCiukzJ/of5zR/0YUAlQUKWCg7m0ZHXW30tSpIo7vseW9nVjXUUNREmyXg==" />
      
      
      <label class="label-form" for="task_name">名称</label>
      <input class="form-control" type="text" name="task[name]" />

      <label class="label-form" for="task_description">詳細</label>
      <textarea rows="5" class="form-control" name="task[description]">
</textarea>
<br>
      <a class="btn btn-lg btn-primary btn-form" <%= link_to "新規登録", users_edit_path%></a>
</form>  </div>
</div>

      
    </div>
  </body>


<!--モーダルウインドウ表示-->
<div id="edit-basic-info" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<% provide(:class_text, 'signup') %>
<% provide(:button_text, '新規作成') %>
<h1>ユーザー登録</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, 'Show') %>
<% provide(:class_text, 'users/show') %>
<% provide(:button_text, 'プロフィール') %>

<div class="container">
  <div class="alert alert-success">ログインしました。</div>
      
<h2>プロフィール</h2>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <table class="table table-bordered" id="table-user">
      <tr>
        <th class="active col-md-3">ID</th>
        <td class="col-md-9">105</td>
      </tr>
      <tr>
        <th class="active">名前</th>
        <td>CHONO</td>
      </tr>
      <tr>
        <th class="active">メールアドレス</th>
        <td>chono0316@gmail.com</td>
      </tr>
      <tr>
        <th class="active">作成日</th>
        <td>2019/07/30 08:03</td>
      </tr>
    </table>
  </div>    
</div>

      
</div>

app/views/users/tasks.html.erb
<% provide(:title, 'Tasks') %>
<div class="container">
      
<h1>ユーザー情報の更新</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <form action="/users/105" accept-charset="UTF-8" method="post"><isnput name="utf8" type="hidden" value="&#x2713;" /><input type="hidden" name="_method" value="patch" /><input type="hidden" name="authenticity_token" value="sRxorYRvWGWcyMRhMWLC1n6+FlPmUu8UmONY1rv8qsWJEaqw2Ny+zagBOttN0ktA+E83o8yyFzUisPfye5eblQ==" />
  

  <label class="label-form" for="user_name">名前</label>
  <input class="form-control" type="text" value="CHONO" name="user[name]" />

  <label class="label-form" for="user_email">メールアドレス</label>
  <input class="form-control" type="email" value="chono0316@gmail.com" name="user[email]" />

  <label class="label-form" for="user_password">パスワード</label>
  <input class="form-control" type="password" name="user[password]" />

  <label class="label-form" for="user_password_confirmation">パスワード再入力</label>
  <input class="form-control" type="password" name="user[password_confirmation]" />

  <input type="submit" name="commit" value="更新" class="btn btn-primary btn-block btn-form" data-disable-with="更新" />
</form>
  </div>
</div>
      
    </div>

app/views/users/tasks.js.erb
$("#tasks").html("<%= escape_javascript(render 'tasks') %>");
$("#tasks").modal("show");

app/views/users/update.html.erb
<% provide(:title, 'Update') %>
<div class="container">
      
<h2>タスク編集</h2>

<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <form action="/users/105/tasks/158" accept-charset="UTF-8" method="post"><input name="utf8" type="hidden" value="&#x2713;" /><input type="hidden" name="_method" value="patch" /><input type="hidden" name="authenticity_token" value="ApfLcR0vQtxED4/uAPWo4sVS70wanBZ2PzBaBVdTmSqUR5Vm1leXZo5+H1ecTlIb3xfucFDvN/0rR4CeMnNJYA==" />
      
      
      <label class="label-form" for="task_name">名称</label>
      <input class="form-control" type="text" value="chono" name="task[name]" />

      <label class="label-form" for="task_description">詳細</label>
      <textarea rows="5" class="form-control" name="task[description]">
Oh YHAH！</textarea>
<br>
      <a class="btn btn-primary btn-form" <%= link_to "更新", users_update1_path%></a>
      <a class="btn btn-default btn-form" <%= link_to "キャンセル", users_edit_path%></a>
</form>  </div>
</div>
      

app/views/users/update1.html.erb
<% provide(:title, 'Update1') %>
<div class="container">
        <div class="alert alert-success">タスクを更新しました。</div>
      
<h2>タスク詳細</h2>

<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <table class="table table-bordered" id="table-task">
      <tbody>
        <tr>
          <th class="active col-md-2">ID</th>
          <td class="col-md-10">158</td>
        </tr>
        <tr>
          <th class="active">名称</th>
          <td>chono</td>
        </tr>
        <tr>
          <th class="active">詳細</th>
          <td>
            Oh YHAH！
          </td>
        </tr>
        <tr>
          <th class="active">作成日</th>
          <td>2019/08/03 23:36</td>
        </tr>
        <tr>
          <th class="active">更新日</th>
          <td>2019/08/03 23:36</td>
        </tr>
      </tbody>
    </table>
    
    <div>
      <a class="btn btn-lg btn-success" <%= link_to "編集", users_update_path%></a>
      <a data-confirm="「chono」を削除します。よろしいですか？" class="btn btn-lg btn-danger" rel="nofollow" data-method="delete" href="/users/105/tasks/158">削除</a>
    </div>
  </div>    
</div>
      
    </div>