config/routes.rb
Rails.application.routes.draw do
  get 'users/crea'

  get 'users/update1' , to: 'users#update1'

  get 'users/update' , to: 'users#update'

  get 'posts/index1', to: 'posts#index1'
  
  get 'users/index', to: 'users#index'

  get 'home/tasks', to: 'users#tasks'
  
  get 'users/edit' , to: 'users#edit'
  
  get 'users/crea' , to: 'users#crea'

  root 'static_pages#top'
  get '/signup', to: 'users#new'
  get '/tasks', to: 'users#tasks'

  # ログイン機能
  get    '/login', to: 'sessions#new'
  post   '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  

  resources :users do
    member do
      get 'edit_basic_info'
      patch 'update_basic_info'
      get 'attendances/edit_one_month'
      patch 'attendances/update_one_month' # この行が追加対象です。
    end
    resources :attendances, only: :update
  end
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-default" id="header">
  <div class="container">
    <%= link_to "Task App", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <p><%= link_to "トップ", root_path , class:"header-list" %></p>
        <% if logged_in? %>
          <p3><%= link_to "タスク作成", users_path , class:"header-list" %></p3>
          <p4 class="dropdown">
            <a1 href="#" class="dropdown-toggle" data-toggle="dropdown" id="dropdown-title">
               CHONO <b class="caret"></b>
            </a1>
            <ul class="dropdown-menu">
              <li class="dropdown-header">ユーザー</li>
              <li><%= link_to "プロフィール", current_user %></li>
              <li><%= link_to "設定", posts_index1_path(current_user)%></li>
              <li class="dropdown-header">タスク</li>
              <li><%= link_to "タスク一覧", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "ログアウト", logout_path, method: :delete %>
              </li>
            </ul>
          </p4>
        <% else %>
         <p4><%= link_to "ログイン", login_path , class:"header-list2" %></p4>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                               'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application',
                               'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, msg| %>
        <div class="alert alert-<%= message_type %>"><%= msg.html_safe %></div>
      <% end %>
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>